version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864899837235.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI="864899837235.dkr.ecr.ap-south-1.amazonaws.com/the7"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ramadevi-the7:1 .
      - echo Pushing the Docker image to ECR...
      - docker push ramadevi-the7:1

artifacts:
  files:
    - '**/*'
  discard-paths: yes
